version: "3.3"
services:

  pihole:
    image: pihole/pihole:latest
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      #- "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ='Europe/Madrid'
      - WEBPASSWORD="CHANGE_THIS_PASSWORD"
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
      - ServerIP=192.168.1.150
      - PROXY_LOCATION=pihole.local
      - VIRTUAL_HOST=pihole.local
      - VIRTUAL_PORT=80
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=http"
      #- "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole_http.rule=Host(`pihole.local`)"
      #- "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
      #- "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.forceslash=true"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
